apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  JWT_SECRET: "ecom_k8s_super_secure_jwt_secret_token_9921_production"
  JWT_EXPIRES_IN: "7d"
  MONGO_AUTH_URI: "mongodb://mongo-service:27017/ecommerce_auth"
  MONGO_PRODUCT_URI: "mongodb://mongo-service:27017/ecommerce_products"
  MONGO_CART_URI: "mongodb://mongo-service:27017/ecommerce_cart"
  MONGO_ORDER_URI: "mongodb://mongo-service:27017/ecommerce_orders"
  MONGO_PAYMENT_URI: "mongodb://mongo-service:27017/ecommerce_payments"
  MONGO_WISHLIST_URI: "mongodb://mongo-service:27017/ecommerce_wishlist"
  MONGO_INVENTORY_URI: "mongodb://mongo-service:27017/ecommerce_inventory"
