apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-worker-deployment
  namespace: ecommerce
  labels:
    app: notification-worker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: notification-worker
  template:
    metadata:
      labels:
        app: notification-worker
    spec:
      containers:
        - name: notification-worker
          image: novacommerce/notification-worker:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: ecommerce-config
            - secretRef:
                name: ecommerce-secrets
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
