apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-deployment
  namespace: ecommerce
  labels:
    app: wishlist-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: wishlist-service
  template:
    metadata:
      labels:
        app: wishlist-service
    spec:
      containers:
        - name: wishlist-service
          image: novacommerce/wishlist-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5006
          env:
            - name: PORT
              value: "5006"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: MONGO_WISHLIST_URI
          envFrom:
            - configMapRef:
                name: ecommerce-config
            - secretRef:
                name: ecommerce-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 5006
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 5006
            initialDelaySeconds: 5
            periodSeconds: 10
