export const TOPICS = Object.freeze({
  ORDER_EVENTS: 'order.events',
  PAYMENT_EVENTS: 'payment.events',
  INVENTORY_EVENTS: 'inventory.events',
  WISHLIST_EVENTS: 'wishlist.events',
  CATALOG_EVENTS: 'catalog.events',
  NOTIFICATION_EVENTS: 'notification.events',
  DEAD_LETTER_QUEUE: 'dead.letter.queue',
});

export const DLQ_TOPICS = Object.freeze({
  'order.events': 'order.events.dlq',
  'payment.events': 'payment.events.dlq',
  'inventory.events': 'inventory.events.dlq',
  'wishlist.events': 'wishlist.events.dlq',
  'catalog.events': 'catalog.events.dlq',
  'notification.events': 'notification.events.dlq',
});

export const EVENT_TYPES = Object.freeze({
  // Order Events
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_CONFIRMED: 'ORDER_CONFIRMED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  ORDER_PROCESSING: 'ORDER_PROCESSING',
  ORDER_SHIPPED: 'ORDER_SHIPPED',
  ORDER_DELIVERED: 'ORDER_DELIVERED',
  ORDER_REFUNDED: 'ORDER_REFUNDED',

  // Payment Events
  PAYMENT_INITIATED: 'PAYMENT_INITIATED',
  PAYMENT_AUTHORIZED: 'PAYMENT_AUTHORIZED',
  PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED',

  // Inventory Events
  INVENTORY_RESERVED: 'INVENTORY_RESERVED',
  INVENTORY_RESERVATION_FAILED: 'INVENTORY_RESERVATION_FAILED',
  INVENTORY_RELEASED: 'INVENTORY_RELEASED',
  INVENTORY_COMMITTED: 'INVENTORY_COMMITTED',
  INVENTORY_RESTOCKED: 'INVENTORY_RESTOCKED',

  // Wishlist Events
  WISHLIST_ITEM_ADDED: 'WISHLIST_ITEM_ADDED',
  WISHLIST_ITEM_REMOVED: 'WISHLIST_ITEM_REMOVED',
  WISHLIST_PRICE_DROPPED: 'WISHLIST_PRICE_DROPPED',
  WISHLIST_MOVED_TO_CART: 'WISHLIST_MOVED_TO_CART',

  // Catalog Events
  CATALOG_PRODUCT_CREATED: 'CATALOG_PRODUCT_CREATED',
  CATALOG_PRODUCT_UPDATED: 'CATALOG_PRODUCT_UPDATED',
  CATALOG_STOCK_REPLENISHED: 'CATALOG_STOCK_REPLENISHED',
  CATALOG_PRICE_CHANGED: 'CATALOG_PRICE_CHANGED',
  CATALOG_FLASH_SALE_STARTED: 'CATALOG_FLASH_SALE_STARTED',

  // Notification Events
  NOTIFICATION_DISPATCH_REQUESTED: 'NOTIFICATION_DISPATCH_REQUESTED',
  NOTIFICATION_EMAIL_SENT: 'NOTIFICATION_EMAIL_SENT',
  NOTIFICATION_SMS_SENT: 'NOTIFICATION_SMS_SENT',
});

export const ALL_TOPICS = [
  ...Object.values(TOPICS),
  ...Object.values(DLQ_TOPICS),
];
